---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Rachel Smith"
pagetitle: "L01 Rachel Smith"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Rachel's Repo](https://github.com/stat301-3-2026-spring/l01-review-rsmith2004)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

1. EDA - learn more about the data, where transformations or recipe steps might be useful

2. Initial Split - partition data into testing and training with reproducibility (seed)

3. Resampling - use a method like vfolds to take multiple samples of the training dataset to improve model accuracy and prevent overfitting.

4. Recipes - a tidymodels data preprocessing framework that involves a list of feature engineering steps

5. Tuning/Fit/Grid - Tuning involves finding optimal values of hyperparameters by setting a grid of hyperparmeter ranges and running a model for each hyperparameter combination (and each resample). Or, for models with no hyperparameter tuning, fitting the model using the recipe and resamples. 

6. Model Comparison - comparing all the models run based on metrics like RMSE for regression problems or ROC/AUC for classification problems, and finding the best metric result to determine best model. 

7. Final Fitting - training best dataset on ALL the training data

8. Model Performance Analysis - evaluating performance based on comparison with the testing data to look at predictive power. 

:::

### Question 2*****

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

Parametric vs nonparametric, one is data-driven, the other relies on a preexisting parameters/shit 

unsupervised doesn't have an outcome variable column 

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

The goal is to describe a characteristic of the data, like the distribution on a variable or the relationship/pattern between multiple variables.  

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

The goal is to infer from data if there is a statistically significant relationship. These models help make inferences, and answers questions like: does what we see in this dataset generalize or demonstrate a causational relationship?

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

The goal is predictive power. Can data be predicted? If we give the model information or use a certain type of model, do we get a good or bad prediction? Is the prediction accurate?

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model usually parametric. It uses existing formulas/equations and makes high assumptions about the data. This method saves time, but assumptions are doing a lot of work.

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

These are data-driven models, very flexible (tree-based) and can fit nontraditional patterns that established equations cannot accurately describe. Not many assumptions are added, data runs the model and model choices.

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models are parametric, they follows some known equation and estimate the set of *parameters*.

Nonparametric models don't assume anything about the data, they are empirically driven models. 

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

A mechanistic model is easier to interpret because it follows a known formula and has a fixed structure. 

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Empirically driven models are more flexible because they fit the pattern of the data, while mechanistic models force the data into an existing formula, which might not fit well at all. 

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models have high bias (points/predictions away from target) and low variance (consistent clutter), whereas empirically driven models have low bias but high variance (very spread out results).

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

A regression problem predicts continuous numeric values, while a classification problem predicts a fixed number of categories/classes.

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

It's useful to stratify by the outcome/target variable because it maintains an equal distribution and representation of variables in the sample that is similar to the actual population, thus reducing sample error. 

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-Fold cross validation takes V folds (with the 1 fold being taken for testing and V-1 folds being used for training), fits and tests the model using that one fold, and then repeats the process until each fold has been a testing set. Then, this process is R times. Each fit has an assessment metric like the RMSE calculated, and the mean RMSE of all those resamples is calculated. We use this technique to help prevent overfitting (through fitting and testing repeatedly) and to help with the bias and variance tradeoff. 

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

Bootstrap resampling is better for smaller datasets, where splitting the data into too many folds might not be feasible. 

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tuning involves adjusting the hyperparameters of a model to improve model accuracy and performance. 

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

The RMSE, or root mean square error,statistical metric measuring the average difference between predicted and actual values

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

